### ISSUE TITLE
Search for 3D assets

### ISSUE THREAD

**Issue by 201flaviosilva** [Mangito/Tree-Simulator#9]
**Description**

The assets should be low poly style

- Tree - Sart search here: https://www.cgtrader.com/3d-models?similar_model_id=3713597
- Landscape

**Comment by Gabriel-Sous-a** [comment]
- https://www.turbosquid.com/3d-models/low-poly-art-nature-pack-lite-3d-model-2235772
- https://www.cgtrader.com/free-3d-models/exterior/landscape/low-poly-forest-nature-set-free-trial
- https://www.turbosquid.com/3d-models/low-poly-stylized-tree-pack-3d-1798413
- https://www.turbosquid.com/3d-models/fantasy-free-model-2098553
- https://www.turbosquid.com/3d-models/3d-model-tree-pack-1964392
